name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  BuildAndTest:
    name: 'Build and test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/playwright-workshop

    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

          # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
          # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: 'Build with Gradle Wrapper'
        run: ./gradlew clean build test

      - name: 'Load test report history'
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: pages
          path: pages

      - name: 'Build test report'
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: 'Publish test report'
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: allure-history